version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - app
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./config/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    build: ./config/mysql
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./config/mysql/mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=docker_user
      - PMA_PASSWORD=docker_pass
    depends_on:
      - mysql
volumes:
  mysql_data:
